language: php

php:
  - 5.3
  - 5.4
  - 5.5
  - 5.6
  - 7.0
  - hhvm
  - nightly

matrix:
  allow_failures:
    - php: 7.0
    - php: hhvm
    - php: nightly

before_script:
  - composer self-update
  - flags=""
  - if [ `phpenv version-name` == "5.3.29" ]; then flags="--ignore-platform-reqs"; fi
  - composer -n install --no-interaction $flags

script: make qa_all
